/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 computer.gltf --transform
Author: sebodeweb (https://sketchfab.com/sebodeweb)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/office-computer-9403093258264563a89d708b906f1b47
Title: Office Computer
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/computer-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 4, 0, 4]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[40.57, 19.54, 8.92]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.MaterialFBXASC032FBXASC0353.geometry} material={materials.MaterialFBXASC032FBXASC0353} position={[-36.63, -67.54, -31.3]} scale={[1.41, 1, 1.7]} />
            <mesh geometry={nodes.MaterialFBXASC032FBXASC0353_1.geometry} material={materials.MaterialFBXASC032FBXASC0353} position={[-60.47, 0.89, -26.24]} scale={[0.07, 2.08, 0.26]} />
            <mesh geometry={nodes.MaterialFBXASC032FBXASC0353_2.geometry} material={materials.MaterialFBXASC032FBXASC0353} position={[-60.47, 0.89, -14.17]} scale={[0.07, 1.86, 0.73]} />
            <mesh geometry={nodes.MaterialFBXASC032FBXASC0353_3.geometry} material={materials.MaterialFBXASC032FBXASC0353} position={[-60.47, 0.89, 12.47]} scale={[0.07, 2.08, 0.26]} />
            <mesh geometry={nodes.MaterialFBXASC032FBXASC0353_4.geometry} material={materials.MaterialFBXASC032FBXASC0353} position={[-60.47, 36.8, -18.9]} scale={[0.04, 0.06, 0.21]} />
            <mesh geometry={nodes.MaterialFBXASC032FBXASC0353_5.geometry} material={materials.MaterialFBXASC032FBXASC0353} position={[-60.47, 30.41, -18.9]} scale={[0.04, 0.06, 0.21]} />
            <mesh geometry={nodes.MaterialFBXASC032FBXASC0353_6.geometry} material={materials.MaterialFBXASC032FBXASC0353} position={[-60.47, -35.5, -18.9]} scale={[0.04, 0.06, 0.21]} />
            <mesh geometry={nodes.MaterialFBXASC032FBXASC0353_7.geometry} material={materials.MaterialFBXASC032FBXASC0353} position={[-60.47, -29.11, -18.9]} scale={[0.04, 0.06, 0.21]} />
            <mesh geometry={nodes.MaterialFBXASC032FBXASC0353_8.geometry} material={materials.MaterialFBXASC032FBXASC0353} position={[-60.47, -35.5, 7.24]} scale={[0.04, 0.06, 0.21]} />
            <mesh geometry={nodes.MaterialFBXASC032FBXASC0353_9.geometry} material={materials.MaterialFBXASC032FBXASC0353} position={[-60.47, -29.11, 7.24]} scale={[0.04, 0.06, 0.21]} />
            <mesh geometry={nodes.MaterialFBXASC032FBXASC0353_10.geometry} material={materials.MaterialFBXASC032FBXASC0353} position={[-60.47, 30.17, 7.24]} scale={[0.04, 0.06, 0.21]} />
            <mesh geometry={nodes.MaterialFBXASC032FBXASC0353_11.geometry} material={materials.MaterialFBXASC032FBXASC0353} position={[-60.47, 36.56, 7.24]} scale={[0.04, 0.06, 0.21]} />
            <mesh geometry={nodes.MaterialFBXASC032FBXASC0353_12.geometry} material={materials.MaterialFBXASC032FBXASC0353} position={[-60.47, 43.39, 3.39]} scale={[0.04, 0.22, 0.08]} />
            <mesh geometry={nodes.MaterialFBXASC032FBXASC0353_13.geometry} material={materials.MaterialFBXASC032FBXASC0353} position={[-60.47, 43.39, -11.56]} scale={[0.04, 0.22, 0.08]} />
            <mesh geometry={nodes.MaterialFBXASC032FBXASC0353_14.geometry} material={materials.MaterialFBXASC032FBXASC0353} position={[-60.47, -41.96, -11.56]} scale={[0.04, 0.22, 0.08]} />
            <mesh geometry={nodes.MaterialFBXASC032FBXASC0353_15.geometry} material={materials.MaterialFBXASC032FBXASC0353} position={[-60.47, -41.96, 3.39]} scale={[0.04, 0.22, 0.08]} />
            <mesh geometry={nodes.MaterialFBXASC032FBXASC0353_16.geometry} material={materials.MaterialFBXASC032FBXASC0353} position={[-53.04, -68.98, 14.92]} scale={[0.25, 0.25, 0.72]} />
            <mesh geometry={nodes.MaterialFBXASC032FBXASC0353_17.geometry} material={materials.MaterialFBXASC032FBXASC0353} position={[-21.89, 0, 29.7]} scale={[1.41, 1.38, 0.17]} />
            <mesh geometry={nodes.MaterialFBXASC032FBXASC0353_18.geometry} material={materials.MaterialFBXASC032FBXASC0353} position={[-53.04, 71.31, 14.92]} scale={[0.25, 0.25, 0.72]} />
            <mesh geometry={nodes.MaterialFBXASC032FBXASC0353_19.geometry} material={materials.MaterialFBXASC032FBXASC0353} position={[-29.41, 80.5, 14.92]} scale={[0.25, 0.25, 0.72]} />
            <mesh geometry={nodes.MaterialFBXASC032FBXASC0353_20.geometry} material={materials.MaterialFBXASC032FBXASC0353} position={[-29.41, -81.08, 14.92]} scale={[0.25, 0.25, 0.72]} />
            <mesh geometry={nodes.MaterialFBXASC032FBXASC0353_21.geometry} material={materials.MaterialFBXASC032FBXASC0353} position={[-29.41, -53.29, 14.92]} scale={[0.25, 0.25, 0.72]} />
            <mesh geometry={nodes.MaterialFBXASC032FBXASC0353_22.geometry} material={materials.MaterialFBXASC032FBXASC0353} position={[-29.41, 54.49, 14.92]} scale={[0.25, 0.25, 0.72]} />
            <mesh geometry={nodes.MaterialFBXASC032FBXASC0353_23.geometry} material={materials.MaterialFBXASC032FBXASC0353} position={[30.5, 72.44, -31.3]} scale={[1.93, 0.82, 1.19]} />
            <mesh geometry={nodes.MaterialFBXASC032FBXASC0353_24.geometry} material={materials.MaterialFBXASC032FBXASC0353} position={[49.38, 50.31, -25.21]} scale={[0.75, 0.45, 1.28]} />
            <mesh geometry={nodes.MaterialFBXASC032FBXASC0353_25.geometry} material={materials.MaterialFBXASC032FBXASC0353} position={[49.38, 50.31, -10.65]} scale={[0.75, 0.45, 1.28]} />
            <mesh geometry={nodes.MaterialFBXASC032FBXASC0353_26.geometry} material={materials.MaterialFBXASC032FBXASC0353} position={[11.14, 50.31, -10.65]} scale={[0.75, 0.45, 1.28]} />
            <mesh geometry={nodes.MaterialFBXASC032FBXASC0353_27.geometry} material={materials.MaterialFBXASC032FBXASC0353} position={[11.14, 50.31, -25.21]} scale={[0.75, 0.45, 1.28]} />
            <mesh geometry={nodes.MaterialFBXASC032FBXASC0353_28.geometry} material={materials.MaterialFBXASC032FBXASC0353} position={[-36.63, 68.89, -31.3]} scale={[1.41, 1, 1.7]} />
          </group>
          <group position={[69.02, 39.48, 21.32]} rotation={[-Math.PI / 2, 0, 0]} scale={1.56}>
            <mesh geometry={nodes.MaterialFBXASC032FBXASC03538.geometry} material={materials.MaterialFBXASC032FBXASC03538} position={[-0.22, -0.54, -8.01]} scale={[0.28, 0.32, 0.28]} />
            <mesh geometry={nodes.MaterialFBXASC032FBXASC03538_1.geometry} material={materials.MaterialFBXASC032FBXASC03538} position={[-1.66, -17.27, 5.32]} rotation={[0, 0, -Math.PI]} scale={[-0.44, 0.44, 0.44]} />
            <mesh geometry={nodes.MaterialFBXASC032FBXASC03538_2.geometry} material={materials.MaterialFBXASC032FBXASC03538} position={[-1.66, 15.27, 5.32]} scale={0.44} />
            <mesh geometry={nodes.MaterialFBXASC032FBXASC03538_3.geometry} material={materials.MaterialFBXASC032FBXASC03538} position={[14.43, -0.53, -6.25]} rotation={[0, 0.1, 0]} scale={[0.06, 0.37, 4.14]} />
            <mesh geometry={nodes.MaterialFBXASC032FBXASC03538_4.geometry} material={materials.MaterialFBXASC032FBXASC03538} position={[20.74, 0.19, 5.4]} rotation={[0, -1.19, 0]} scale={[0.4, 0.4, 0.17]} />
          </group>
          <mesh geometry={nodes.MaterialFBXASC032FBXASC0354_ncl1_1.geometry} material={materials.MaterialFBXASC032FBXASC0354_ncl1_1} position={[16.04, 51, -18.41]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[0.2, 0.24, 0.14]} />
          <mesh geometry={nodes.MaterialFBXASC032FBXASC0354_ncl1_1_1.geometry} material={materials.MaterialFBXASC032FBXASC0354_ncl1_1} position={[14.69, 51.4, 11.99]} rotation={[-Math.PI / 2, 0.15, -Math.PI]} scale={[0.53, 0.72, 0.72]} />
          <mesh geometry={nodes.MaterialFBXASC032FBXASC0352.geometry} material={materials.MaterialFBXASC032FBXASC0352} position={[76.12, 26.41, -66.14]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[0.51, 0.51, 0.36]} />
          <mesh geometry={nodes.MaterialFBXASC032FBXASC0354_ncl1_1_2.geometry} material={materials.MaterialFBXASC032FBXASC0354_ncl1_1} position={[6.86, 51.12, -34.45]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[0.51, 1.18, 0.51]} />
          <mesh geometry={nodes.MaterialFBXASC032FBXASC0354.geometry} material={materials.MaterialFBXASC032FBXASC0354} position={[-22.59, 88.17, 28.6]} rotation={[-Math.PI / 2, -0.26, -Math.PI / 2]} scale={[0.26, 0.46, 0.46]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/computer-transformed.glb')
