/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Impact.gltf --transform
Author: MooKorea (https://sketchfab.com/MooKorea)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/higokumaru-honkai-impact-3rd-0e903387170846f5939adaa0c277b91b
Title: Higokumaru | Honkai Impact 3rd
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Impact-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[-100.4, 806.75, -294.3]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Body_Backup004_Clothes_0.geometry} material={materials.Clothes} />
          <mesh geometry={nodes.Body_Backup004_Clothes_0_1.geometry} material={materials.Clothes} />
          <mesh geometry={nodes.Body_Backup004_Clothes_0_2.geometry} material={materials.Clothes} />
          <mesh geometry={nodes.Body_Backup004_Clothes_Metal_0.geometry} material={materials.Clothes} />
        </group>
        <mesh geometry={nodes.Body_Backup002_Skin_0.geometry} material={materials.Skin} position={[-100.4, 806.75, -294.3]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Body_Backup003_Hair_0.geometry} material={materials.Hair} position={[-100.4, 806.75, -294.3]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Body_Backup005_Fire_0.geometry} material={materials.Fire} position={[-100.4, 806.75, -294.3]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('/Impact-transformed.glb')
